[versions]
agp = "8.1.1"
kotlin = "1.9.21"
compose = "1.6.0-rc01"
androidx-appcompat = "1.6.1"
activity-compose = "1.7.0"
datetime = "0.5.0"
material-kolor = "1.2.8"
decompose = "2.2.0-compose-experimental"
essenty = "1.3.0"
serialization="1.6.2"
atomicfu="0.23.1"
#maven-publish="0.25.3"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "material-kolor" }
decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }
essenty = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
atomicfuPlugin= { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "atomicfu" }
atomicfu= { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
